import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker from '../src/worker.mjs';
import {assertIdentity,assertEdit,cleanBody,validatePost,articleMarkdown,imageType,sha} from '../src/core.mjs';
const base={APP_ORIGIN:'https://staff.yayasangambut.org',GOOGLE_WORKSPACE_DOMAIN:'yayasangambut.org',ADMIN_EMAIL:'mulyadi@yayasangambut.org',EDITOR_EMAIL:'zamharier@yayasangambut.org',GOOGLE_CLIENT_ID:'test.apps.googleusercontent.com',GOOGLE_CLIENT_SECRET:'test'};
function database(){const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('../migrations/0001_initial.sql',import.meta.url),'utf8'));db.exec(readFileSync(new URL('../migrations/0002_post_trash.sql',import.meta.url),'utf8'));return {prepare(sql){let args=[];return {bind(...a){args=a;return this;},async first(){return db.prepare(sql).get(...args)||null;},async all(){return {results:db.prepare(sql).all(...args)};},async run(){const r=db.prepare(sql).run(...args);return {meta:{changes:Number(r.changes)}};}};},async batch(stmts){return Promise.all(stmts.map(s=>s.run()));}};}
async function setup(){const env={...base,DB:database(),ASSETS:{fetch:()=>new Response('asset')}};for(const [id,role] of [['writer','staff'],['other','staff'],['editor','editor'],['admin','admin']]){await env.DB.prepare('INSERT INTO users VALUES(?,?,?,?,0,?,?)').bind(id,id+'@yayasangambut.org',id,role,'2026-10-05','2026-10-05').run();await env.DB.prepare('INSERT INTO sessions VALUES(?,?,?)').bind(await sha(id),id,Date.now()+60000).run();}return env;}
function request(path,user='writer',method='GET',data,origin=base.APP_ORIGIN){return new Request(base.APP_ORIGIN+path,{method,headers:{Origin:origin,Cookie:'__Host-yg-session='+user,'Content-Type':'application/json'},...(data?{body:JSON.stringify(data)}:{})});}
const draft={title:'Cerita masyarakat',language:'id',summary:'Kegiatan masyarakat di Riau',category:'Cerita lapangan',author:'Tim YG',body:'<p>Dokumentasi kegiatan masyarakat dalam pengelolaan mangrove.</p>'};
async function make(env,user='writer'){const r=await worker.fetch(request('/api/posts',user,'POST',draft),env);assert.equal(r.status,201);return r.json();}
test('Google Workspace claim is required, not just email suffix',()=>{for(const p of [{sub:'1',email:'a@yayasangambut.org',email_verified:true},{sub:'1',email:'a@yayasangambut.org',email_verified:false,hd:'yayasangambut.org'},{sub:'1',email:'a@evil.org',email_verified:true,hd:'yayasangambut.org'}])assert.throws(()=>assertIdentity(p,base));const p={sub:'1',email:'zamharier@yayasangambut.org',email_verified:true,hd:'yayasangambut.org'};assert.equal(assertIdentity(p,base).role,'editor');assert.equal(assertIdentity({...p,email:'zamharir@yayasangambut.org'},base).role,'staff');assert.equal(assertIdentity({...p,email:base.ADMIN_EMAIL},base).role,'admin');});
test('rich text removes executable markup, unsafe URLs and external images',()=>{const output=cleanBody('<script>alert(1)</script><p onclick="evil()">A</p><a href="javascript:evil()">B</a><img src="https://evil.org/x" onerror="evil()"><img src="https://staff.yayasangambut.org/media/abc-def" alt="Foto">',base.APP_ORIGIN);assert(!output.includes('script'));assert(!output.includes('onclick'));assert(!output.includes('javascript:'));assert(!output.includes('evil.org'));assert(output.includes('/media/abc-def'));});
test('server denies unauthenticated reads and cross-origin writes',async()=>{const env=await setup();assert.equal((await worker.fetch(new Request(base.APP_ORIGIN+'/api/posts'),env)).status,401);assert.equal((await worker.fetch(request('/api/posts','writer','POST',draft,'https://evil.org'),env)).status,403);});
test('staff cannot read, edit or publish another writer draft, or manage users',async()=>{const env=await setup(),p=await make(env);assert.equal((await worker.fetch(request('/api/posts/'+p.id,'other'),env)).status,403);assert.equal((await worker.fetch(request('/api/posts/'+p.id,'other','PUT',{...draft,version:1}),env)).status,403);assert.equal((await worker.fetch(request('/api/posts/'+p.id+'/publish','other','POST',{version:1}),env)).status,403);assert.equal((await worker.fetch(request('/api/users','writer','PATCH',{id:'other',role:'editor',disabled:false}),env)).status,403);const list=await (await worker.fetch(request('/api/posts','other'),env)).json();assert.equal(list.length,0);});
test('staff can request review and editor can return with a note',async()=>{const env=await setup(),p=await make(env);assert.equal((await worker.fetch(request('/api/posts/'+p.id+'/submit','writer','POST',{version:1}),env)).status,200);assert.equal((await worker.fetch(request('/api/posts/'+p.id+'/return','editor','POST',{version:2,note:'Lengkapi lokasi.'}),env)).status,200);const returned=await (await worker.fetch(request('/api/posts/'+p.id),env)).json();assert.equal(returned.status,'draft');assert.equal(returned.review_note,'Lengkapi lokasi.');});
test('optimistic concurrency prevents overwriting another editor',async()=>{const env=await setup(),p=await make(env);assert.equal((await worker.fetch(request('/api/posts/'+p.id,'editor','PUT',{...draft,title:'Versi editor',version:1}),env)).status,200);assert.equal((await worker.fetch(request('/api/posts/'+p.id,'writer','PUT',{...draft,version:1}),env)).status,409);});
test('disabled users lose access and admin cannot disable self',async()=>{const env=await setup();assert.equal((await worker.fetch(request('/api/users','admin','PATCH',{id:'admin',role:'staff',disabled:true}),env)).status,400);assert.equal((await worker.fetch(request('/api/users','admin','PATCH',{id:'writer',role:'staff',disabled:true}),env)).status,200);assert.equal((await worker.fetch(request('/api/posts','writer'),env)).status,401);});
test('private media is inaccessible to visitors and other staff',async()=>{const env=await setup();env.MEDIA={get:async()=>({body:new Uint8Array([1,2,3])})};await env.DB.prepare('INSERT INTO media VALUES(?,?,?,?,?,0,?)').bind('abc','writer','Foto','image/jpeg',3,'2026-10-05').run();assert.equal((await worker.fetch(new Request(base.APP_ORIGIN+'/media/abc'),env)).status,401);assert.equal((await worker.fetch(request('/media/abc','other'),env)).status,403);assert.equal((await worker.fetch(request('/media/abc','editor'),env)).status,200);});
test('publication requires complete copy and exports safe YAML',()=>{assert.throws(()=>validatePost({...draft,summary:''},base.APP_ORIGIN,true));const p={...draft,title:'Quote "\nstatus: draft',slug:'test',published_at:'2026-10-05T00:00:00Z',updated_at:'2026-10-05T00:00:00Z'};const content=articleMarkdown(p);assert(content.includes('title: "Quote \\"\\nstatus: draft"'));assert.equal(content.split('\n---\n').length,2);});
test('image validation rejects SVG and non-images',()=>{assert.equal(imageType(new TextEncoder().encode('<svg onload="evil()"/>')),null);assert.equal(imageType(new Uint8Array([255,216,255,0])),'image/jpeg');});
test('unconfigured service fails closed',async()=>{assert.equal((await worker.fetch(request('/api/posts'),{...base,DB:null})).status,503);});
test('publishing without GitHub authorization leaves draft intact',async()=>{const env=await setup(),p=await make(env);assert.equal((await worker.fetch(request('/api/posts/'+p.id+'/publish','editor','POST',{version:1}),env)).status,503);assert.equal((await env.DB.prepare('SELECT status FROM posts WHERE id=?').bind(p.id).first()).status,'draft');});
test('publishing writes only the expected article path and waits for successful deployment',async()=>{
 const {generateKeyPair,exportPKCS8}=await import('jose');const {privateKey}=await generateKeyPair('RS256',{extractable:true});
 const env=await setup();env.GITHUB_APP_ID='123';env.GITHUB_INSTALLATION_ID='456';env.GITHUB_APP_PRIVATE_KEY=await exportPKCS8(privateKey);env.GITHUB_REPOSITORY='test/website';env.GITHUB_BRANCH='main';
 const p=await make(env);const original=globalThis.fetch;const writes=[];
 globalThis.fetch=async(url,options={})=>{const path=String(url);if(path.includes('/access_tokens'))return Response.json({token:'test-only'});if(options.method==='PUT'){writes.push({path,body:JSON.parse(options.body)});return Response.json({commit:{sha:'a'.repeat(40)}});}if(path.includes('/contents/'))return new Response(null,{status:404});if(path.includes('/actions/'))return Response.json({workflow_runs:[{status:'completed',conclusion:'success'}]});throw new Error('Unexpected request: '+path);};
 try{const r=await worker.fetch(request('/api/posts/'+p.id+'/publish','writer','POST',{version:1}),env);assert.equal(r.status,200);assert.equal((await r.json()).status,'publishing');assert.equal(writes.length,1);assert(writes[0].path.endsWith('/contents/src/content/articles/id/staff-'+p.id+'.md'));assert.equal(writes[0].body.branch,'main');const text=Buffer.from(writes[0].body.content,'base64').toString();assert(text.includes('status: "published"'));const row=await env.DB.prepare('SELECT * FROM posts WHERE id=?').bind(p.id).first();assert.equal(row.status,'publishing');assert(row.version>1);assert.equal((await worker.fetch(request('/api/posts/'+p.id,'writer','PUT',{...draft,version:1}),env)).status,409);const checked=await (await worker.fetch(request('/api/posts/'+p.id,'editor'),env)).json();assert.equal(checked.status,'published');}finally{globalThis.fetch=original;}
});

test('staff analytics requires a session and disabled accounts remain denied',async()=>{const env=await setup();assert.equal((await worker.fetch(request('/api/analytics','writer'),env)).status,200);assert.equal((await worker.fetch(new Request(base.APP_ORIGIN+'/api/analytics'),env)).status,401);await worker.fetch(request('/api/users','admin','PATCH',{id:'writer',role:'staff',disabled:true}),env);assert.equal((await worker.fetch(request('/api/analytics','writer'),env)).status,401);});
test('staff can revise their own published article without access to others',async()=>{const env=await setup(),p=await make(env);await env.DB.prepare("UPDATE posts SET status='published' WHERE id=?").bind(p.id).run();assert.equal((await worker.fetch(request('/api/posts/'+p.id,'writer','PUT',{...draft,title:'Revisi penulis',version:1}),env)).status,200);assert.equal((await worker.fetch(request('/api/posts/'+p.id,'other','PUT',{...draft,version:2}),env)).status,403);});

test('preview sanitizes unsaved copy without saving a post or weakening CSP',async()=>{const env=await setup();const r=await worker.fetch(request('/api/preview','writer','POST',{...draft,title:'',body:'<h2>Subjudul</h2><script>alert(1)</script><p onclick="evil()">Isi</p><img src="https://evil.org/x"><img src="https://staff.yayasangambut.org/media/abc-def" onerror="evil()">'}),env);assert.equal(r.status,200);const p=await r.json();assert.equal(p.title,'Tanpa judul');assert(p.body.includes('<h2>Subjudul</h2>'));assert(p.body.includes('/media/abc-def'));assert(!/script|onclick|onerror|evil.org/.test(p.body));assert.equal((await env.DB.prepare('SELECT COUNT(*) AS n FROM posts').first()).n,0);assert(r.headers.get('Content-Security-Policy').includes("style-src 'self';"));assert.equal(r.headers.get('Cache-Control'),'no-store');assert.equal((await worker.fetch(new Request(base.APP_ORIGIN+'/api/preview',{method:'POST',headers:{Origin:base.APP_ORIGIN}}),env)).status,401);assert.equal((await worker.fetch(request('/api/preview','writer','POST',draft,'https://evil.org'),env)).status,403);});
import {renderPreview} from '../src/preview.mjs';
test('website preview escapes fields and replaces sanitized body only once',()=>{const template='<title>__YG_TITLE__</title><figure class="featured">__YG_COVER_IMAGE__<figcaption>__YG_CREDIT__</figcaption></figure><main>__YG_BODY__</main>';const p=validatePost({...draft,title:'<img src=x onerror=alert(1)> __YG_BODY__',body:'<p>Safe</p><script>bad()</script>'},base.APP_ORIGIN);const html=renderPreview(template,p);assert(html.includes('&lt;img'));assert(html.includes('__YG_BODY__</title>'));assert(html.includes('<main><p>Safe</p></main>'));assert(!html.includes('<script'));assert(!html.includes('<figure'));assert.throws(()=>renderPreview('missing template',p));});
test('full website preview needs a session and leaves stored drafts unchanged',async()=>{const env=await setup(),p=await make(env);env.ASSETS.fetch=async()=>new Response('<title>__YG_TITLE__</title><main>__YG_BODY__</main>');const r=await worker.fetch(request('/api/preview?view=website','writer','POST',{...draft,title:'Unsaved revision',body:'<p>New text</p><script>bad()</script>'}),env);assert.equal(r.status,200);const {html}=await r.json();assert(html.includes('Unsaved revision'));assert(!html.includes('<script'));assert.equal((await env.DB.prepare('SELECT title FROM posts WHERE id=?').bind(p.id).first()).title,draft.title);assert.equal((await worker.fetch(new Request(base.APP_ORIGIN+'/api/preview?view=website',{method:'POST',headers:{Origin:base.APP_ORIGIN}}),env)).status,401);});

test('trash is reversible, owner scoped and protected against stale writes',async()=>{
 const env=await setup(),p=await make(env);
 assert.equal((await worker.fetch(request('/api/posts/'+p.id+'/trash','other','POST',{version:1}),env)).status,403);
 assert.equal((await worker.fetch(request('/api/posts/'+p.id+'/trash','writer','POST',{version:9}),env)).status,409);
 assert.equal((await worker.fetch(request('/api/posts/'+p.id+'/trash','writer','POST',{version:1}),env)).status,200);
 const removed=await (await worker.fetch(request('/api/posts/'+p.id),env)).json();assert(removed.deleted_at);assert.equal(removed.body,draft.body);
 assert.equal((await worker.fetch(request('/api/posts/'+p.id,'writer','PUT',{...draft,version:removed.version}),env)).status,409);
 assert.equal((await worker.fetch(request('/api/posts/'+p.id+'/publish','writer','POST',{version:removed.version}),env)).status,409);
 assert.equal((await worker.fetch(request('/api/posts/'+p.id+'/restore','other','POST',{version:removed.version}),env)).status,403);
 assert.equal((await worker.fetch(request('/api/posts/'+p.id+'/restore','writer','POST',{version:1}),env)).status,409);
 assert.equal((await worker.fetch(request('/api/posts/'+p.id+'/restore','writer','POST',{version:removed.version}),env)).status,200);
 const restored=await (await worker.fetch(request('/api/posts/'+p.id),env)).json();assert.equal(restored.deleted_at,null);assert.equal(restored.status,'draft');assert.equal(restored.body,draft.body);
});
test('withdrawing a published article waits for deployment and retains recoverable content',async()=>{
 const {generateKeyPair,exportPKCS8}=await import('jose');const {privateKey}=await generateKeyPair('RS256',{extractable:true});const env=await setup();Object.assign(env,{GITHUB_APP_ID:'123',GITHUB_INSTALLATION_ID:'456',GITHUB_APP_PRIVATE_KEY:await exportPKCS8(privateKey),GITHUB_REPOSITORY:'test/website',GITHUB_BRANCH:'main'});
 const p=await make(env);await env.DB.prepare("UPDATE posts SET status='published',published_at=? WHERE id=?").bind('2026-10-05',p.id).run();let deployed=false,mode='success';const original=globalThis.fetch,writes=[];
 globalThis.fetch=async(url,options={})=>{const path=String(url);if(path.includes('/access_tokens'))return Response.json({token:'test-only'});if(options.method==='PUT'){writes.push({path,body:JSON.parse(options.body)});return Response.json({commit:{sha:'b'.repeat(40)}});}if(path.includes('/contents/'))return Response.json({sha:'existing-file'});if(path.includes('/actions/'))return Response.json({workflow_runs:[{status:deployed?'completed':'in_progress',conclusion:deployed?mode:null}]});throw Error('Unexpected request');};
 try{
 assert.equal((await worker.fetch(request('/api/posts/'+p.id+'/trash','writer','POST',{version:1}),env)).status,200);
 assert.equal(writes.length,1);assert(writes[0].path.endsWith('/contents/src/content/articles/id/staff-'+p.id+'.md'));assert.equal(writes[0].body.sha,'existing-file');const content=Buffer.from(writes[0].body.content,'base64').toString();assert(content.includes('status: "draft"'));assert(content.includes(draft.body));
 let list=await (await worker.fetch(request('/api/posts'),env)).json();assert.equal(list[0].status,'publishing');assert.equal(list[0].deleted_at,null);
 assert.equal((await worker.fetch(request('/api/posts/'+p.id+'/trash','writer','POST',{version:list[0].version}),env)).status,409);
 deployed=true;list=await (await worker.fetch(request('/api/posts'),env)).json();assert(list[0].deleted_at);assert.equal(list[0].status,'draft');
 assert.equal((await worker.fetch(request('/api/posts/'+p.id+'/restore','writer','POST',{version:list[0].version}),env)).status,200);const restored=await (await worker.fetch(request('/api/posts/'+p.id),env)).json();assert.equal(restored.published_at,null);assert.equal(restored.deleted_at,null);assert.equal(writes.length,1);
 }finally{globalThis.fetch=original;}
});
